# Generated by Django 3.2.6 on 2021-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(default=False, verbose_name="نویسنده است"),
        ),
    ]
