# Generated by Django 4.0.2 on 2022-03-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان ابزارک')),
                ('body', models.TextField(max_length=1000, verbose_name='کد')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
                ('order', models.IntegerField(verbose_name='ترتیب')),
            ],
        ),
    ]
