# Generated by Django 4.0.2 on 2022-03-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'ابزارک', 'verbose_name_plural': 'ابزارک ها'},
        ),
    ]
