# Generated by Django 4.0.2 on 2022-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('top', 'بالا'), ('left', 'چپ')], max_length=10, verbose_name='جایگاه'),
        ),
    ]
