# Generated by Django 4.0.2 on 2022-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_module_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['position', 'order'], 'verbose_name': 'ابزارک', 'verbose_name_plural': 'ابزارک ها'},
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.CharField(choices=[('top', 'بالا'), ('left', 'چپ'), ('foot1', 'پایین راست'), ('foot2', 'پایین وسط'), ('foot3', 'پایین چپ')], max_length=10, verbose_name='جایگاه'),
        ),
    ]
