# Generated by Django 3.2.6 on 2022-03-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'برگه', 'verbose_name_plural': 'برگه ها'},
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=25, unique=True, verbose_name='نامک'),
        ),
    ]
