# Generated by Django 3.1.7 on 2021-03-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shop",
            new_name="Products",
        ),
    ]
