# Generated by Django 3.1.7 on 2021-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_getcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getcode',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
