# Generated by Django 3.1.7 on 2021-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_product_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("slug", models.SlugField()),
            ],
        ),
    ]
