# Generated by Django 3.1.7 on 2021-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=20, unique=True),
        ),
    ]
