# Generated by Django 3.1.7 on 2021-07-19 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_auto_20210710_1827"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GetCode",
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "مقاله", "verbose_name_plural": "مقالات"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.AddField(
            model_name="category",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ساخت"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="images", verbose_name="تصویر شاخص"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="published",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=20, unique=True, verbose_name="نامک"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("d", "پیش نویس"), ("p", "منتشر شده")],
                max_length=1,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=20, unique=True, verbose_name="نامک"
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
