# Generated by Django 3.1.7 on 2021-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_auto_20210719_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(to="web.Category"),
        ),
    ]
