# Generated by Django 3.1.7 on 2021-07-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.IntegerField(default="0", verbose_name="جایگاه"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(to="web.Category", verbose_name="دسته بندی"),
        ),
    ]
