# Generated by Django 3.1.7 on 2021-08-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_auto_20210720_1105"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-published"],
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="web.category",
                verbose_name="دسته والد",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(
                related_name="articles", to="web.Category", verbose_name="دسته بندی"
            ),
        ),
    ]
