# Generated by Django 3.2.6 on 2021-11-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_blog_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
