# Generated by Django 3.2.6 on 2022-03-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='title',
        ),
    ]
