# Generated by Django 3.2.6 on 2022-03-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.comment', verbose_name='نظرات'),
        ),
    ]
